all:
  vars:
     skupper_option_kubeconfig: "{{ lookup('ansible.builtin.env', 'KUBECONFIG') | default(lookup('ansible.builtin.env', 'HOME') ~ '/.kube/config', true) }}"
  children:
    public:
      hosts:
        artemis-sender-site:
          ansible_connection: local
          skupper_option_namespace: artemis-sender-site
          skupper_init_site_name: artemis-sender-site
          skupper_service_list:
            - name: artemis-acceptor
              ports: [5672]
              protocol: tcp
        artemis-receiver-site:
          ansible_connection: local
          skupper_option_namespace: artemis-receiver-site
          skupper_init_site_name: artemis-receiver-site
          skupper_service_list:
            - name: artemis-acceptor
              ports: [5672]
              protocol: tcp
        artemis-broker-site:
          ansible_connection: local
          skupper_option_namespace: artemis-broker-site
          skupper_init_site_name: artemis-broker-site
          skupper_init_enable_flow_collector: "true"
          skupper_init_enable_console: "true"
          skupper_init_console_passowrd: "admin"
          skupper_link_list:
            - host: artemis-sender-site
            - host: artemis-receiver-site
          skupper_service_list:
            - name: artemis-acceptor
              ports: [5672]
              protocol: tcp
              targets:
                - type: service
                  name: ex-aao-amqp-0-svc
