---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-message-receiver
  namespace: artemis-receiver-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amqp-message-receiver
  template:
    metadata:
      labels:
        app: amqp-message-receiver
    spec:
      containers:
        - name: amqp-client
          image: quay.io/rhmessagingqe/cli-java:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          command: ["/bin/sh", "-c"]
          args:
            - |
              while :; do
                cli-qpid-receiver -b amqp://artemis-acceptor:5672 -c 1000 -a myQ --log-msgs dict
              done
