---
- name: Installing ActiveMQ Broker
  kubernetes.core.k8s:
    src: "{{ item }}"
    namespace: "artemis-broker-site"
    state: present
  loop: "{{ broker_files }}"
  loop_control:
    loop_var: item
    pause: 2
